version: "3"

services:
  database:
    image: mongo
    container_name: polls_for_devs_server_mongo
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./.docker/polls_for_devs_server_mongo:/data/db

