version: '3'

services:
  polls_for_devs_node:
    image: node
    container_name: polls_for_devs_node
    ports:
      - 3333:3333
    build: .
    restart: on-failure
    volumes:
      - .:/home/polls_for_devs_node
      - '/home/polls_for_devs_node/node_modules'
    networks:
      - polls_for_devs
    depends_on:
      - polls_for_devs_mongo

  polls_for_devs_mongo:
    image: mongo
    container_name: polls_for_devs_mongo
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - ./.docker/polls_for_devs_mongo:/data/db
    networks:
      - polls_for_devs

networks:
  polls_for_devs:
    driver: bridge
